root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  entrypoint = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules", "tests"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
